# Generated by Django 5.2.15 on 2026-06-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictionHistoru',
            new_name='PredictionHistory',
        ),
    ]
